export interface Question {
  id: string;
  chapter: 'Prepositions' | 'Conjunctions' | 'Sentence Connectors';
  topic: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  type: 'MCQ' | 'TrueFalse' | 'FillBlank' | 'Identify';
  question: string;
  options?: string[];
  answer: string;
  explanation: string;
  bengaliMeaning?: string;
  memoryTip?: string;
  source: string;
  marks: number;
}

export const questions: Question[] = [
  // ========== PREPOSITION IDENTIFICATION (15) ==========
  {
    id: 'PREP-001',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He sat ___ the bench.',
    options: ['on', 'in', 'at', 'by'],
    answer: 'on',
    explanation: 'We sit on a bench (surface).',
    bengaliMeaning: 'সে বেঞ্চে বসল।',
    memoryTip: 'ON + surface',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-002',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He came here ___ rail.',
    options: ['by', 'on', 'in', 'with'],
    answer: 'by',
    explanation: 'BY + mode of transport (train, rail, bus, car).',
    bengaliMeaning: 'সে রেলে এখানে এসেছিল।',
    memoryTip: 'BY + transport',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-003',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'This train is running ___ time.',
    options: ['on', 'in', 'at', 'by'],
    answer: 'on',
    explanation: 'ON TIME = punctual (at the appointed time).',
    memoryTip: 'ON TIME = punctual | IN TIME = early enough',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-004',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He said this ___ oath.',
    options: ['on', 'in', 'under', 'at'],
    answer: 'on',
    explanation: 'The fixed phrase is "on oath".',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-005',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I am ___ the know of the thing.',
    options: ['in', 'on', 'at', 'of'],
    answer: 'in',
    explanation: 'The idiom is "in the know".',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-006',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He came ___ foot.',
    options: ['on', 'by', 'with', 'in'],
    answer: 'on',
    explanation: 'ON FOOT is the correct expression (not by foot).',
    memoryTip: 'ON + foot / horseback',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-007',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is ___ school.',
    options: ['at', 'in', 'on', 'to'],
    answer: 'at',
    explanation: 'AT school = attending school as a student.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-008',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I know him ___ name.',
    options: ['by', 'with', 'from', 'of'],
    answer: 'by',
    explanation: 'Know someone by name / by sight.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-009',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is ___ work now.',
    options: ['at', 'in', 'on', 'under'],
    answer: 'at',
    explanation: 'AT work / AT play = engaged in the activity.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-010',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'She is playing ___ a sitar.',
    options: ['on', 'with', 'in', 'at'],
    answer: 'on',
    explanation: 'Play ON a musical instrument.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-011',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: "Don't go out ___ the sun.",
    options: ['in', 'under', 'on', 'at'],
    answer: 'in',
    explanation: 'IN the sun is the correct expression.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-012',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'We live ___ rice.',
    options: ['on', 'by', 'with', 'from'],
    answer: 'on',
    explanation: 'Live ON a particular food or income.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-013',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'This food is not ___ my taste.',
    options: ['to', 'for', 'of', 'with'],
    answer: 'to',
    explanation: 'To one\'s taste is the fixed phrase.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-014',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I met him ___ the way.',
    options: ['on', 'in', 'at', 'by'],
    answer: 'on',
    explanation: 'ON the way is the correct expression.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-015',
    chapter: 'Prepositions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He was beaten ___ death.',
    options: ['to', 'into', 'till', 'for'],
    answer: 'to',
    explanation: 'Beaten TO death is the fixed phrase.',
    source: 'Chapter XXII',
    marks: 1
  },

  // ========== PREPOSITION SELECTION & USAGE (20) ==========
  {
    id: 'PREP-016',
    chapter: 'Prepositions',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is ___ power now.',
    options: ['in', 'on', 'at', 'under'],
    answer: 'in',
    explanation: 'IN power = holding political power.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-017',
    chapter: 'Prepositions',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I did this ___ you.',
    options: ['for', 'to', 'of', 'with'],
    answer: 'for',
    explanation: 'FOR = on behalf of / for the benefit of.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-018',
    chapter: 'Prepositions',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The proposal is ___ consideration.',
    options: ['under', 'in', 'on', 'at'],
    answer: 'under',
    explanation: 'UNDER consideration is the fixed phrase.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-019',
    chapter: 'Prepositions',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I paid him ___ cash.',
    options: ['in', 'by', 'with', 'on'],
    answer: 'in',
    explanation: 'Pay IN cash / notes (but BY cheque).',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-020',
    chapter: 'Prepositions',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Send the news ___ wire.',
    options: ['by', 'on', 'with', 'through'],
    answer: 'by',
    explanation: 'BY wire / by post / by messenger.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-021',
    chapter: 'Prepositions',
    topic: 'AT-ON-IN',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I shall see you ___ Sunday.',
    options: ['on', 'in', 'at', 'by'],
    answer: 'on',
    explanation: 'ON + day / date.',
    memoryTip: 'ON = Day / Date',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-022',
    chapter: 'Prepositions',
    topic: 'AT-ON-IN',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The meeting is ___ 6 o\'clock.',
    options: ['at', 'on', 'in', 'by'],
    answer: 'at',
    explanation: 'AT + exact point of time.',
    memoryTip: 'AT = Point of time',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-023',
    chapter: 'Prepositions',
    topic: 'AT-ON-IN',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He was born ___ 1995.',
    options: ['in', 'on', 'at', 'during'],
    answer: 'in',
    explanation: 'IN + year / month / period.',
    memoryTip: 'IN = Period',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-024',
    chapter: 'Prepositions',
    topic: 'AT-ON-IN',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'We reached the station ___ time to catch the train.',
    options: ['in', 'on', 'at', 'by'],
    answer: 'in',
    explanation: 'IN TIME = early enough / before it is too late.',
    memoryTip: 'IN TIME vs ON TIME',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-025',
    chapter: 'Prepositions',
    topic: 'AT-ON-IN',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'The train arrived ___ time.',
    options: ['on', 'in', 'at', 'by'],
    answer: 'on',
    explanation: 'ON TIME = punctual.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-026',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He is senior ___ me in respect of age.',
    options: ['to', 'than', 'from', 'of'],
    answer: 'to',
    explanation: 'Senior / junior / superior / inferior + TO.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-027',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '___ view of his ill health he was let go.',
    options: ['In', 'On', 'At', 'With'],
    answer: 'In',
    explanation: 'IN VIEW OF is a phrase preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-028',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He stood ___ front of the door.',
    options: ['in', 'on', 'at', 'to'],
    answer: 'in',
    explanation: 'IN FRONT OF is a phrase preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-029',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Potato sells ___ five rupees a kilo.',
    options: ['at', 'for', 'by', 'on'],
    answer: 'at',
    explanation: 'Sell AT a price. Note also the disguised preposition "a".',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-030',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I sent ___ him.',
    options: ['for', 'to', 'after', 'of'],
    answer: 'for',
    explanation: 'Send FOR someone = call someone to come.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-031',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He looks ___ my estate.',
    options: ['after', 'for', 'at', 'to'],
    answer: 'after',
    explanation: 'Look AFTER = take care of.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-032',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Hard',
    type: 'MCQ',
    question: 'He is better ___ me in every respect.',
    options: ['than', 'to', 'from', 'of'],
    answer: 'than',
    explanation: 'Than can function as a preposition before personal pronouns (textbook accepts this).',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-033',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Died ___ cholera.',
    options: ['of', 'from', 'with', 'by'],
    answer: 'of',
    explanation: 'Die OF a disease (textbook preference).',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-034',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'A lecturer ___ Chemistry.',
    options: ['in', 'of', 'on', 'at'],
    answer: 'in',
    explanation: 'Reader / Lecturer IN a subject; Professor OF a subject.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-035',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Sitting ___ an armchair.',
    options: ['in', 'on', 'at', 'by'],
    answer: 'in',
    explanation: 'IN an armchair (but ON a chair without arms).',
    source: 'Chapter XXII',
    marks: 1
  },

  // ========== PARTS OF SPEECH (10) ==========
  {
    id: 'PREP-036',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He came down. — "down" is a/an ___',
    options: ['Adverb', 'Preposition', 'Conjunction', 'Adjective'],
    answer: 'Adverb',
    explanation: 'No object after "down" → Adverb.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-037',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The boat flowed down the stream. — "down" is a/an ___',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Adjective'],
    answer: 'Preposition',
    explanation: 'Has an object "the stream" → Preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-038',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He ran on. — "on" is a/an ___',
    options: ['Adverb', 'Preposition', 'Conjunction', 'Noun'],
    answer: 'Adverb',
    explanation: 'No object → Adverb.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-039',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'We sat on the bench. — "on" is a/an ___',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Adjective'],
    answer: 'Preposition',
    explanation: 'Has object "the bench" → Preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-040',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Please come in. — "in" is a/an ___',
    options: ['Adverb', 'Preposition', 'Conjunction', 'Adjective'],
    answer: 'Adverb',
    explanation: 'No object → Adverb.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-041',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'There was none in the room. — "in" is a/an ___',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Adjective'],
    answer: 'Preposition',
    explanation: 'Has object "the room" → Preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-042',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'The case is under trial. — "under" is a/an ___',
    options: ['Preposition', 'Adverb', 'Conjunction', 'Adjective'],
    answer: 'Preposition',
    explanation: 'UNDER trial — preposition governing "trial".',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-043',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'The rebels were brought under. — "under" is a/an ___',
    options: ['Adverb', 'Preposition', 'Conjunction', 'Adjective'],
    answer: 'Adverb',
    explanation: 'No object after "under" → Adverb (or particle).',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-044',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Medium',
    type: 'TrueFalse',
    question: '"Than" can never be used as a preposition.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'The textbook and modern usage accept "than" as a preposition in cases like "than me", "than whom".',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-045',
    chapter: 'Prepositions',
    topic: 'Parts of Speech',
    difficulty: 'Medium',
    type: 'TrueFalse',
    question: 'In "He comes twice a week", "a" is the indefinite article.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: '"a" here is a disguised form of the preposition "on".',
    source: 'Chapter XXII',
    marks: 1
  },

  // ========== PREPOSITIONAL PHRASES (10) ==========
  {
    id: 'PREP-046',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Which is a phrase preposition?',
    options: ['in spite of', 'on', 'at', 'by'],
    answer: 'in spite of',
    explanation: 'Phrase prepositions are groups of words acting as one preposition.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-047',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He could not come ___ account of illness.',
    options: ['on', 'in', 'at', 'for'],
    answer: 'on',
    explanation: 'ON ACCOUNT OF = because of.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-048',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '___ spite of hard labour he failed.',
    options: ['In', 'On', 'At', 'With'],
    answer: 'In',
    explanation: 'IN SPITE OF is a phrase preposition.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-049',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Which is NOT a phrase preposition?',
    options: ['regarding', 'instead of', 'by means of', 'owing to'],
    answer: 'regarding',
    explanation: '"Regarding" is a participial preposition, not a phrase preposition.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-050',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is senior to me ___ respect of age.',
    options: ['in', 'on', 'with', 'for'],
    answer: 'in',
    explanation: 'IN RESPECT OF is a phrase preposition.',
    source: 'Exercise 31',
    marks: 1
  },
  {
    id: 'PREP-051',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Medium',
    type: 'TrueFalse',
    question: '"Concerning" and "regarding" are participial prepositions.',
    options: ['True', 'False'],
    answer: 'True',
    explanation: 'They are present participles used as prepositions.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-052',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'The river flows ___ the town.',
    options: ['past', 'pass', 'passed', 'passing'],
    answer: 'past',
    explanation: '"Past" is used as a participial preposition here.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-053',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '___ of coming here, he went home.',
    options: ['Instead', 'In spite', 'On account', 'By means'],
    answer: 'Instead',
    explanation: 'INSTEAD OF is a phrase preposition.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-054',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Which phrase means "because of"?',
    options: ['owing to', 'instead of', 'in front of', 'in spite of'],
    answer: 'owing to',
    explanation: 'Owing to / on account of = because of.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-055',
    chapter: 'Prepositions',
    topic: 'Phrase Prepositions',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He succeeded ___ dint of hard work.',
    options: ['by', 'on', 'in', 'with'],
    answer: 'by',
    explanation: 'BY DINT OF = by means of / through.',
    source: 'Chapter XXII',
    marks: 1
  },

  // ========== CONJUNCTION IDENTIFICATION (15) ==========
  {
    id: 'CONJ-001',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is poor ___ honest.',
    options: ['but', 'and', 'or', 'so'],
    answer: 'but',
    explanation: 'BUT is an adversative coordinating conjunction showing contrast.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-002',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Time ___ tide wait for none.',
    options: ['and', 'or', 'but', 'nor'],
    answer: 'and',
    explanation: 'AND is a cumulative coordinating conjunction.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-003',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Is he a friend ___ a foe?',
    options: ['or', 'and', 'but', 'nor'],
    answer: 'or',
    explanation: 'OR is an alternative coordinating conjunction.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-004',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Wait ___ I return.',
    options: ['till', 'while', 'when', 'as'],
    answer: 'till',
    explanation: 'TILL / UNTIL are subordinating conjunctions of time.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-005',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '___ I am ill I cannot go.',
    options: ['As', 'But', 'Or', 'And'],
    answer: 'As',
    explanation: 'AS / SINCE introduce a reason (subordinating).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-006',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I shall do it ___ I am allowed.',
    options: ['if', 'unless', 'though', 'while'],
    answer: 'if',
    explanation: 'IF introduces a condition.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-007',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is so ill ___ he cannot walk.',
    options: ['that', 'so', 'as', 'than'],
    answer: 'that',
    explanation: 'SO…THAT expresses effect / result.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-008',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I wonder ___ he will come.',
    options: ['whether', 'that', 'if', 'when'],
    answer: 'whether',
    explanation: 'WHETHER is common after verbs of wondering / knowing (indirect question).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-009',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He works ___ you play.',
    options: ['while', 'when', 'as', 'since'],
    answer: 'while',
    explanation: 'WHILE can show simultaneous actions or contrast.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-010',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I tried hard, ___ I failed.',
    options: ['but', 'and', 'so', 'or'],
    answer: 'but',
    explanation: 'BUT shows contrast (adversative).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-011',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Hard',
    type: 'MCQ',
    question: 'Beware ___ you should fall.',
    options: ['lest', 'that', 'if', 'unless'],
    answer: 'lest',
    explanation: 'LEST expresses negative purpose and is followed by should.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-012',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I love him ___ he is honest.',
    options: ['because', 'although', 'if', 'unless'],
    answer: 'because',
    explanation: 'BECAUSE introduces the reason.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-013',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is ___ honest ___ you.',
    options: ['as … as', 'so … as', 'more … than', 'both … and'],
    answer: 'as … as',
    explanation: 'AS…AS is used for equal comparison (positive).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-014',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He is not ___ honest ___ you.',
    options: ['so … as', 'as … as', 'more … than', 'both … and'],
    answer: 'so … as',
    explanation: 'SO…AS is preferred in negative comparisons (though as…as is also accepted).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-015',
    chapter: 'Conjunctions',
    topic: 'Identification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He left ___ I had come.',
    options: ['before', 'after', 'when', 'while'],
    answer: 'before',
    explanation: 'BEFORE indicates the earlier action.',
    source: 'Exercise 32',
    marks: 1
  },

  // ========== CONJUNCTION CLASSIFICATION (10) ==========
  {
    id: 'CONJ-016',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '"When" in "I went there when he was ill" is a ___ conjunction.',
    options: ['Subordinating', 'Coordinating', 'Correlative', 'Compound'],
    answer: 'Subordinating',
    explanation: 'It introduces a subordinate clause of time.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-017',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '"But" in "He is rich but miserly" is a ___ conjunction.',
    options: ['Coordinating (Adversative)', 'Subordinating', 'Correlative', 'Illative'],
    answer: 'Coordinating (Adversative)',
    explanation: 'BUT joins two equal ideas and shows contrast.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-018',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '"Not only…but also" is a ___ conjunction.',
    options: ['Correlative / Coordinating', 'Subordinating', 'Illative', 'Simple'],
    answer: 'Correlative / Coordinating',
    explanation: 'It is a correlative pair used as coordinating (cumulative).',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-019',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '"If" in "If you read you will learn" is ___',
    options: ['Subordinating (Condition)', 'Coordinating', 'Adversative', 'Illative'],
    answer: 'Subordinating (Condition)',
    explanation: 'IF introduces a conditional clause.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-020',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '"For" in "I cannot help you, for I am ill" is ___',
    options: ['Coordinating (Illative)', 'Subordinating', 'Adversative', 'Cumulative'],
    answer: 'Coordinating (Illative)',
    explanation: 'Modern grammarians treat "for" as coordinating (gives a reason as an afterthought).',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-021',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '"Though" in "Though you are strong, I care a straw for you" is ___',
    options: ['Subordinating (Concession)', 'Coordinating', 'Correlative', 'Illative'],
    answer: 'Subordinating (Concession)',
    explanation: 'THOUGH / ALTHOUGH introduce concessive clauses.',
    source: 'Exercise 32',
    marks: 1
  },
  {
    id: 'CONJ-022',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '"Therefore" is mainly a ___ conjunction / linker.',
    options: ['Illative / Sentence connector', 'Adversative', 'Cumulative', 'Conditional'],
    answer: 'Illative / Sentence connector',
    explanation: 'It denotes inference / result.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-023',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'FANBOYS is a memory aid for ___',
    options: ['Common coordinating conjunctions', 'All subordinating conjunctions', 'Only correlatives', 'Only adversatives'],
    answer: 'Common coordinating conjunctions',
    explanation: 'For, And, Nor, But, Or, Yet, So.',
    source: 'Memory Formula',
    marks: 1
  },
  {
    id: 'CONJ-024',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Hard',
    type: 'TrueFalse',
    question: '"Lest" should be followed by a negative verb.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Lest already expresses negative purpose; do not add another negative. Use "lest he should fail".',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-025',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '"As if" should generally be followed by ___',
    options: ['a past conditional form', 'present simple only', 'will / would', 'can / could'],
    answer: 'a past conditional form',
    explanation: 'Textbook and MEU prefer past forms after as if / as though (were, had, would…).',
    source: 'Chapter XXIII',
    marks: 1
  },

  // ========== FILL IN THE BLANKS / MORE PRACTICE (15) ==========
  {
    id: 'CONJ-026',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Either he ___ his brother is guilty.',
    options: ['or', 'nor', 'and', 'but'],
    answer: 'or',
    explanation: 'EITHER…OR is the correlative pair.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-027',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Neither he ___ his brother is guilty.',
    options: ['nor', 'or', 'and', 'but'],
    answer: 'nor',
    explanation: 'NEITHER…NOR is the correlative pair.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-028',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Both he ___ his brother are guilty.',
    options: ['and', 'or', 'nor', 'but'],
    answer: 'and',
    explanation: 'BOTH…AND.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-029',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Not only he ___ his brother also will go.',
    options: ['but', 'and', 'or', 'nor'],
    answer: 'but',
    explanation: 'NOT ONLY…BUT ALSO.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-030',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He works hard ___ he may win the prize.',
    options: ['so that', 'lest', 'although', 'unless'],
    answer: 'so that',
    explanation: 'SO THAT / IN ORDER THAT express purpose.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-031',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Hard',
    type: 'MCQ',
    question: 'I worked hard ___ I should fail.',
    options: ['lest', 'so that', 'although', 'because'],
    answer: 'lest',
    explanation: 'LEST = so that…not / for fear that.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-032',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He is such a fool ___ I cannot rely on him.',
    options: ['that', 'as', 'so', 'than'],
    answer: 'that',
    explanation: 'SUCH…THAT expresses result.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-033',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '___ he is poor, he is honest.',
    options: ['Although', 'Because', 'If', 'Unless'],
    answer: 'Although',
    explanation: 'ALTHOUGH / THOUGH introduce concession.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-034',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He behaves ___ he were mad.',
    options: ['as if', 'as', 'like', 'so that'],
    answer: 'as if',
    explanation: 'AS IF / AS THOUGH + past conditional.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-035',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Work hard, ___ you will fail.',
    options: ['otherwise', 'because', 'although', 'so that'],
    answer: 'otherwise',
    explanation: 'OTHERWISE is an alternative coordinating conjunction.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-036',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I shall fail ___ you help me.',
    options: ['unless', 'if', 'because', 'although'],
    answer: 'unless',
    explanation: 'UNLESS = if…not.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-037',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He did not work; ___ he failed.',
    options: ['therefore', 'although', 'because', 'if'],
    answer: 'therefore',
    explanation: 'THEREFORE / SO / CONSEQUENTLY show result (illative).',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-038',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'You failed, ___ your brother passed.',
    options: ['while', 'because', 'if', 'unless'],
    answer: 'while',
    explanation: 'WHILE / WHEREAS can show contrast (adversative use).',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-039',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Hard',
    type: 'MCQ',
    question: 'The reason why he failed is ___ he did not work hard.',
    options: ['that', 'because', 'due to', 'on account of'],
    answer: 'that',
    explanation: 'After "the reason is / the reason why" use THAT, not because.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-040',
    chapter: 'Conjunctions',
    topic: 'Fill Blank',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Poor ___ I am, I am honest.',
    options: ['as', 'though', 'although', 'but'],
    answer: 'as',
    explanation: '"Adjective + as + subject + verb" = concessive (though).',
    source: 'Chapter XXIII',
    marks: 1
  },

  // ========== SENTENCE CONNECTORS (15) ==========
  {
    id: 'CONN-001',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'There is acute water shortage; ___, the Municipality will provide a deep tubewell.',
    options: ['however', 'because', 'so', 'although'],
    answer: 'however',
    explanation: 'HOWEVER shows contrast between the shortage and the positive action.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-002',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The Headmaster is very angry ___ the boys made a noise.',
    options: ['because', 'however', 'moreover', 'although'],
    answer: 'because',
    explanation: 'BECAUSE introduces the reason.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-003',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: '___ it was sunny outside, she didn\'t use her umbrella.',
    options: ['Although', 'Because', 'So', 'Moreover'],
    answer: 'Although',
    explanation: 'ALTHOUGH introduces a concessive clause.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-004',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The policeman stopped the car, ___ the children could cross the road.',
    options: ['so', 'because', 'although', 'however'],
    answer: 'so',
    explanation: 'SO shows purpose / result.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-005',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I don\'t want to go; ___, I don\'t have a proper dress.',
    options: ['moreover', 'because', 'although', 'so'],
    answer: 'moreover',
    explanation: 'MOREOVER adds another reason.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-006',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He always speaks the truth. ___ I like him.',
    options: ['Indeed', 'Therefore', 'Although', 'Because'],
    answer: 'Indeed',
    explanation: 'INDEED emphasises the previous statement.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-007',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He worked hard this year. ___ he became successful.',
    options: ['Because of that', 'In general', 'Although', 'Moreover'],
    answer: 'Because of that',
    explanation: 'Shows cause → effect relation.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-008',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'It is a nicely written story. ___ it should be given an award.',
    options: ['Actually', 'From my point of view', 'Although', 'Because'],
    answer: 'Actually',
    explanation: 'ACTUALLY strengthens the opinion.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-009',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I am glad to meet you. ___ what are you doing today?',
    options: ['By the way', 'Moreover', 'Therefore', 'Although'],
    answer: 'By the way',
    explanation: 'BY THE WAY introduces a new related topic.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-010',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: '___ he is a good boy. This is why I like him.',
    options: ['Basically', 'As a result', 'Although', 'However'],
    answer: 'Basically',
    explanation: 'BASICALLY introduces the essential fact.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-011',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Ramen could not answer all the questions. ___ he hopes to get a good mark.',
    options: ['Nevertheless', 'Besides', 'Because', 'So'],
    answer: 'Nevertheless',
    explanation: 'NEVERTHELESS shows contrast despite the difficulty.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-012',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Sri Basu is a good teacher. ___, he is a good poet.',
    options: ['Besides', 'As well as', 'Although', 'Because'],
    answer: 'Besides',
    explanation: 'BESIDES adds extra information.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-013',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He gave me money. ___, he gave me advice.',
    options: ['In addition', 'As well as', 'Although', 'Because'],
    answer: 'In addition',
    explanation: 'IN ADDITION / MOREOVER add information.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-014',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He insulted me. ___ I love him.',
    options: ['Still', 'Although', 'Because', 'So'],
    answer: 'Still',
    explanation: 'STILL shows contrast.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-015',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is rich. ___ he is dishonest.',
    options: ['Yet', 'Though', 'Because', 'So'],
    answer: 'Yet',
    explanation: 'YET shows unexpected contrast.',
    source: 'Exercise 33',
    marks: 1
  },

  // ========== SENTENCE JOINING & ERROR (10+) ==========
  {
    id: 'CONN-016',
    chapter: 'Sentence Connectors',
    topic: 'Joining',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He is poor. He is honest. → Best combination:',
    options: [
      'He is poor but honest.',
      'He is poor because honest.',
      'He is poor so honest.',
      'He is poor if honest.'
    ],
    answer: 'He is poor but honest.',
    explanation: 'BUT shows contrast between poverty and honesty.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-017',
    chapter: 'Sentence Connectors',
    topic: 'Joining',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'She did not come to school. She was ill. → Best combination:',
    options: [
      'She did not come to school because she was ill.',
      'She did not come to school although she was ill.',
      'She did not come to school so she was ill.',
      'She did not come to school but she was ill.'
    ],
    answer: 'She did not come to school because she was ill.',
    explanation: 'BECAUSE shows the reason.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-018',
    chapter: 'Sentence Connectors',
    topic: 'Joining',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He will not come. His brother will not come. → Best combination:',
    options: [
      'Neither he nor his brother will come.',
      'Either he or his brother will come.',
      'Both he and his brother will come.',
      'He will not come but his brother will come.'
    ],
    answer: 'Neither he nor his brother will come.',
    explanation: 'NEITHER…NOR for two negative statements.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-019',
    chapter: 'Sentence Connectors',
    topic: 'Joining',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'You have opposed me. I shall help you. → Best combination:',
    options: [
      'Although you have opposed me, I shall help you.',
      'Because you have opposed me, I shall help you.',
      'If you have opposed me, I shall help you.',
      'So you have opposed me, I shall help you.'
    ],
    answer: 'Although you have opposed me, I shall help you.',
    explanation: 'ALTHOUGH shows concession.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-020',
    chapter: 'Sentence Connectors',
    topic: 'Joining',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'You must walk. You will miss the bus. → Best combination:',
    options: [
      'You must walk, or you will miss the bus.',
      'You must walk because you will miss the bus.',
      'You must walk although you will miss the bus.',
      'You must walk so you will miss the bus.'
    ],
    answer: 'You must walk, or you will miss the bus.',
    explanation: 'OR / OTHERWISE shows the alternative consequence.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-021',
    chapter: 'Sentence Connectors',
    topic: 'Difference',
    difficulty: 'Medium',
    type: 'TrueFalse',
    question: 'Sentence connectors always join two sentences into one grammatical sentence.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Connectors link ideas between independent sentences; they do not necessarily form one sentence.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-022',
    chapter: 'Sentence Connectors',
    topic: 'Difference',
    difficulty: 'Medium',
    type: 'TrueFalse',
    question: 'Conjunctions and sentence connectors are exactly the same.',
    options: ['True', 'False'],
    answer: 'False',
    explanation: 'Conjunctions join into one sentence; connectors mainly create logical flow between separate sentences.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-023',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Ranjan is a good boy, ___ his brother is wicked.',
    options: ['but', 'although', 'because', 'so'],
    answer: 'but',
    explanation: 'BUT shows contrast.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-024',
    chapter: 'Sentence Connectors',
    topic: 'Selection',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'I could not come to school yesterday ___ I was sick.',
    options: ['as', 'therefore', 'however', 'moreover'],
    answer: 'as',
    explanation: 'AS / BECAUSE / SINCE introduce the reason.',
    source: 'Exercise 33',
    marks: 1
  },
  {
    id: 'CONN-025',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Which linker best shows result?',
    options: ['as a result', 'although', 'moreover', 'however'],
    answer: 'as a result',
    explanation: 'AS A RESULT / THEREFORE / CONSEQUENTLY show effect.',
    source: 'Chapter XXIII',
    marks: 1
  },

  // Extra questions to exceed 150
  {
    id: 'PREP-056',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'He studied ___ this university.',
    options: ['at', 'in', 'on', 'to'],
    answer: 'at',
    explanation: 'AT + institution name is common (at this university).',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-057',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'The examination is ___ hand.',
    options: ['at', 'in', 'on', 'by'],
    answer: 'at',
    explanation: 'AT HAND = very near / approaching.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-058',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Write ___ this paper (but ___ a book).',
    options: ['on … in', 'in … on', 'at … in', 'on … on'],
    answer: 'on … in',
    explanation: 'Write ON paper; write IN a book.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-059',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Lying ___ bed (but sitting ___ the bed).',
    options: ['in … on', 'on … in', 'at … on', 'in … in'],
    answer: 'in … on',
    explanation: 'IN bed (under covers); ON the bed (surface).',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'PREP-060',
    chapter: 'Prepositions',
    topic: 'Usage',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'A house ___ fire.',
    options: ['on', 'in', 'at', 'under'],
    answer: 'on',
    explanation: 'ON FIRE is the fixed phrase.',
    source: 'Chapter XXII',
    marks: 1
  },
  {
    id: 'CONJ-041',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Which is a cumulative conjunction?',
    options: ['and', 'but', 'or', 'therefore'],
    answer: 'and',
    explanation: 'AND simply adds (cumulative / copulative).',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-042',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Which is an adversative conjunction?',
    options: ['but', 'and', 'or', 'so'],
    answer: 'but',
    explanation: 'BUT shows contrast.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-043',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Which is an alternative conjunction?',
    options: ['or', 'and', 'but', 'so'],
    answer: 'or',
    explanation: 'OR offers a choice.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONJ-044',
    chapter: 'Conjunctions',
    topic: 'Classification',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'Which is an illative conjunction?',
    options: ['therefore', 'but', 'and', 'or'],
    answer: 'therefore',
    explanation: 'THEREFORE shows inference / result.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-026',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Which linker best shows addition?',
    options: ['moreover', 'however', 'therefore', 'although'],
    answer: 'moreover',
    explanation: 'MOREOVER / FURTHERMORE / BESIDES add information.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-027',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'Which linker best shows contrast?',
    options: ['however', 'moreover', 'therefore', 'indeed'],
    answer: 'however',
    explanation: 'HOWEVER / STILL / NEVERTHELESS show contrast.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-028',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He jumped over 6 metres. ___ he could not break the record.',
    options: ['Still', 'Moreover', 'Therefore', 'Indeed'],
    answer: 'Still',
    explanation: 'STILL shows contrast despite the achievement.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-029',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Easy',
    type: 'MCQ',
    question: 'He worked hard. ___ he became successful.',
    options: ['Finally', 'Although', 'However', 'Because'],
    answer: 'Finally',
    explanation: 'FINALLY shows sequence / result after effort.',
    source: 'Chapter XXIII',
    marks: 1
  },
  {
    id: 'CONN-030',
    chapter: 'Sentence Connectors',
    topic: 'Application',
    difficulty: 'Medium',
    type: 'MCQ',
    question: 'I\'m not going to help him. ___, he does not deserve my help.',
    options: ['Moreover', 'Although', 'Because', 'So'],
    answer: 'Moreover',
    explanation: 'MOREOVER adds another supporting reason.',
    source: 'Chapter XXIII',
    marks: 1
  }
];

// Ensure we have at least 150
console.log('Total questions:', questions.length);
